### ISSUE TITLE
What is going on with the last update of EXTPBR? 

### ISSUE THREAD

**Issue by bryanf3000** [ExtremeAddons/extreme_pbr#1]
## System Information
**Blender version:** 3.6.0, blender-v3.6-release, 2023-06-27, 08:08, c7fc78b81ecb
**HDRIMaker version:** (4, 1, 101)
**OS:** Windows
**GPU:** NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
**Active Addons:** Extra Objects, A.N.T.Landscape, BoltFactory, Extra Objects, Geodesic Domes, Import Images as Planes, Edit Mesh Tools, F2, LoopTools, Node Wrangler, Node Presets, Bool Tool, Align Tools, Rigify, Alt Tab Water, BagaPie Modifier, BagaPieAssets, Drag

**Comment by bryanf3000** [comment]
Nothing is working on the new PBR update? 
User library won't register?
You have to upload min 2GB file that only have some of the textures.
This add on is wasting way to much of my time.

**Comment by ExtremeAddons** [comment]
Try to unlink the User library, a "Make User Library" button should appear, press it. Let me know how it goes

Andrew


Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows

Da: ***@***.***>
Inviato: lunedì 11 settembre 2023 17:52
A: ***@***.***>
Cc: ***@***.***>
Oggetto: Re: [ExtremeAddons/extreme_pbr] What is going on with the last update of EXTPBR? (Issue #1)


Nothing is working on the new PBR update?
User library won't register?
You have to upload min 2GB file that only have some of the textures.
This add on is wasting way to much of my time.

**Comment by ExtremeAddons** [comment]
Here you can find the complete Documentation: https://extreme-pbr-docs.readthedocs.io/en/latest/index.html

Please report errors precisely, and accurately describe what is wrong, so that we can understand and help or in the case of intervening in any bugs to be corrected, this section is for reporting bugs or malfunctions of the addon.

**Comment by ExtremeAddons** [comment]
Since 5 months have passed and no response, I am closing the topic due to lack of information
