### ISSUE TITLE
Not working when Port over Blender 3.6 setting to Blender 4.0

### ISSUE THREAD

**Issue by dannyteoac** [ExtremeAddons/extreme_pbr#2]
Download both Blender 4.0 and 4.1 version with workable 3.6 setting.  It don't show the PBR  library path for setting.  Restart blender and blender prompt error. 
![Blender Preferences 10_10_2023 1_36_12 PM](https://github.com/ExtremeAddons/extreme_pbr/assets/40867293/2d0fbe43-a98b-4330-b055-d570eb1329fa)

**Comment by ExtremeAddons** [comment]
I'm aware, the version you are using was not intended for Blender 4.0 

By tomorrow he will release a version of Extreme PBR beta 4.1.110 which works on Blender 4.0 and also on previous versions 👍
